### ISSUE TITLE
dam break demo(InitialisationZone)

### ISSUE THREAD

**Issue by kamakiri1225** [jaheyns/CfdOF#183] opened 2024-09-04 02:27 UTC
We ask that you please use this interface to contribute constructively to this free, open-source project by reporting carefully tested problems that you find in the software. Please provide as much information as you can and, if at all possible,
**include a small test case which allows developers to reproduce the issue**.

![image](https://github.com/user-attachments/assets/b79ddefb-f633-4c8b-b002-a7749214e61f)

The dam break demo is not working.
I believe the issue lies with the InitialisationZone.
When I click on InitialisationZone, I get the following screen.
Is this the expected behavior?

![image](https://github.com/user-attachments/assets/69e85d24-20c3-4f2f-a750-0bf8a3efba19)

In this YouTube video, the demo is working correctly. However, in the latest version of cfdOF, it does not behave as shown in the video.

https://www.youtube.com/watch?v=w7ZKDwps1p4&list=PL9H9jQE7y0a5jhlyACRzsdfnx-42AYCCX&index=15

As a result, the setFieldsDict is not being created, and the dam break analysis cannot be performed correctly.

**Comment by oliveroxtoby** [comment] 2024-09-04 06:53
I can't reproduce this behaviour - it seems to be working fine for me. I note that your initialisationZone appears to be outside the CfdAnalysis object, so your file may be broken in some way. It's hard to say without the .FCStd file.

If you would like me to investigate further, please provide the saved state as a FCStd file, and **exact** instructions on how to reproduce the problem.

**Comment by kamakiri1225** [comment] 2024-09-04 10:45
Thank you for your response. It worked correctly with FreeCAD 0.21.2. Could this be an issue of version compatibility? For now, it seems like everything will work without any problems. Thank you.

![image](https://github.com/user-attachments/assets/99be66a8-4e65-4ef1-82b2-19fbc9a4ad2c)

**Comment by oliveroxtoby** [comment] 2024-09-04 14:00
It could be. I will close this since v0.20 won't be supported for much longer anyway.

**Closed by oliveroxtoby** 2024-09-04 14:00 UTC
